name: build

on:
  push:
    branches:
      - main
      - "feat/**"
  pull_request:

jobs:
  windows-x64:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset windows-x64-release

      - name: Build
        run: cmake --build --preset windows-x64-release

      - name: Test
        run: ctest --preset windows-x64-release
